# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: EthanSteensmaFinal

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Run Playwright tests
      uses: microsoft/playwright-github-action@v1.5.5
    - name: Restore dependencies
      run: dotnet restore ./src/SoftwareTesting.sln
    - name: Build
      run: dotnet build ./src/SoftwareTesting.sln --no-restore
    - name: Test
      run: dotnet test ./src/PlaywrightTests/PlaywrightTests.csproj --no-build --verbosity normal --logger "trx;LogFileName=xtests.trx"
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          /home/runner/work/SoftwareTesting/SoftwareTesting/src/XUnitExamples/TestResults/xtests.trx
