# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/SoftwareTesting.sln
    - name: Playwirhgt dep
      run: dotnet add package Microsoft.Playwright.MSTest
    - name: Build
      run: dotnet build ./src/SoftwareTesting.sln --no-restore
    - name: Install browser
      run: pwsh bin/Debug/net7.0/playwright.ps1 install
    - name: Test
      run: dotnet test ./src/PlaywrightTests/PlaywrightTests.csproj
